# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb09c2a874c7865acde280e665f62bde"
name = "bibekshop"
handle = "bibekshop"
application_url = "https://vanilla-thrown-reviews-authentication.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-de70b9af.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vanilla-thrown-reviews-authentication.trycloudflare.com/auth/callback",
  "https://vanilla-thrown-reviews-authentication.trycloudflare.com/auth/shopify/callback",
  "https://vanilla-thrown-reviews-authentication.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
